// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDBmiL0BU3HsQo8n4mwxeIb7s1_UW1KFG0',
    appId: '1:86321879683:web:UNKNOWN_APP_ID',
    messagingSenderId: '86321879683',
    projectId: 'simulated-d40be',
    authDomain: 'simulated-d40be.firebaseapp.com',
    storageBucket: 'simulated-d40be.firebasestorage.app',
    measurementId: 'G-MEASUREMENT_ID',
    databaseURL:
        'https://simulated-d40be-default-rtdb.asia-southeast1.firebasedatabase.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDBmiL0BU3HsQo8n4mwxeIb7s1_UW1KFG0',
    appId: '1:86321879683:android:dee281775e831256c159b6',
    messagingSenderId: '86321879683',
    projectId: 'simulated-d40be',
    storageBucket: 'simulated-d40be.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDBmiL0BU3HsQo8n4mwxeIb7s1_UW1KFG0',
    appId: '1:86321879683:ios:UNKNOWN_APP_ID',
    messagingSenderId: '86321879683',
    projectId: 'simulated-d40be',
    storageBucket: 'simulated-d40be.firebasestorage.app',
    iosBundleId: 'com.gr4.pbl6_app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDBmiL0BU3HsQo8n4mwxeIb7s1_UW1KFG0',
    appId: '1:86321879683:macos:UNKNOWN_APP_ID',
    messagingSenderId: '86321879683',
    projectId: 'simulated-d40be',
    storageBucket: 'simulated-d40be.firebasestorage.app',
    iosBundleId: 'com.gr4.pbl6_app.RunnerTests',
  );
}
